import {StyleSheet, Dimensions} from 'react-native';
import {FONTS, COLORS} from '../../../constants';
import {RFValue} from 'react-native-responsive-fontsize';

const {width: SCREEN_WIDTH, height: SCREEN_HEIGHT} = Dimensions.get('window');
const HERO_HEIGHT = SCREEN_HEIGHT * 0.28;
const IS_TABLET = SCREEN_WIDTH > 600;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.pinkybg,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: RFValue(25),
  },

  // Hero Section Styles
  heroSectionWrapper: {
    marginBottom: RFValue(18),
    position: 'relative',
  },
  heroSection: {
    height: HERO_HEIGHT,
  },
  heroBackground: {
    width: '100%',
    height: '100%',
  },
  heroBackgroundImage: {
    resizeMode: 'cover',
  },
  heroGradient: {
    flex: 1,
    alignItems: 'flex-start',
    paddingHorizontal: RFValue(20),
  },
  heroContent: {
    width: '100%',
    alignItems: 'flex-start',
  },
  heroTitle: {
    fontSize: RFValue(24),
    fontFamily: FONTS.funPlayBold,
    color: '#fff',
    marginBottom: RFValue(8),
    textShadowColor: 'rgba(0, 0, 0, 0.8)',
    textShadowOffset: {width: 0, height: RFValue(2)},
    textShadowRadius: RFValue(8),
    letterSpacing: RFValue(0.5),
    marginTop: RFValue(50),
  },
  heroDescription: {
    fontSize: RFValue(14),
    fontFamily: FONTS.fontFamilyBold,
    color: '#fff',
    textShadowColor: 'rgba(0, 0, 0, 0.6)',
    textShadowOffset: {width: 0, height: RFValue(2)},
    textShadowRadius: RFValue(5),
  },
  waveContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    width: SCREEN_WIDTH,
    height: RFValue(60),
    zIndex: 100,
    overflow: 'hidden',
  },

  // Content Wrapper
  contentWrapper: {
    paddingHorizontal: RFValue(12),
  },

  // Two Column Layout
  twoColumnLayout: {
    flexDirection: IS_TABLET ? 'row' : 'column',
    gap: RFValue(12),
    alignItems: 'flex-start',
  },

  // Right Column: Cart Items
  rightColumn: {
    flex: IS_TABLET ? 1.3 : 1,
    width: IS_TABLET ? 'auto' : '100%',
    minWidth: IS_TABLET ? RFValue(300) : '100%',
  },
  cartSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: RFValue(12),
    paddingHorizontal: RFValue(2),
  },
  cartSectionHeaderContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: RFValue(8),
  },
  cartIconWrapper: {
    width: RFValue(32),
    height: RFValue(32),
    borderRadius: RFValue(8),
    backgroundColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 2,
    shadowColor: COLORS.primary,
    shadowOffset: {width: 0, height: RFValue(1)},
    shadowOpacity: 0.25,
    shadowRadius: RFValue(3),
  },
  cartSectionTitle: {
    fontSize: RFValue(16),
    fontFamily: FONTS.funPlayBold,
    color: COLORS.primary,
    letterSpacing: RFValue(0.2),
  },
  cartBadge: {
    backgroundColor: COLORS.secondary,
    borderRadius: RFValue(10),
    minWidth: RFValue(24),
    height: RFValue(24),
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: RFValue(6),
    elevation: 2,
    shadowColor: COLORS.secondary,
    shadowOffset: {width: 0, height: RFValue(1)},
    shadowOpacity: 0.25,
    shadowRadius: RFValue(2),
  },
  cartBadgeText: {
    fontSize: RFValue(11),
    color: '#fff',
    fontFamily: FONTS.fontFamilyBold,
  },
  cartItemsList: {
    gap: RFValue(10),
  },

  // Premium Card Design
  cartItemCard: {
    backgroundColor: '#fff',
    borderRadius: RFValue(11),
    overflow: 'hidden',
    elevation: 2,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowOffset: {width: 0, height: RFValue(1)},
    shadowRadius: RFValue(4),
    borderWidth: 1,
    borderColor: '#F5F5F5',
    marginHorizontal: RFValue(1),
  },
  cardTopBorder: {
    height: RFValue(3),
    width: '100%',
  },
  cardContent: {
    flexDirection: 'row',
    padding: RFValue(8),
    gap: RFValue(8),
  },
  imageWrapper: {
    width: RFValue(70),
    height: RFValue(70),
    borderRadius: RFValue(9),
    overflow: 'hidden',
    backgroundColor: '#F7F7F7',
    position: 'relative',
  },
  cartItemImage: {
    width: '100%',
    height: '100%',
  },
  sizeBadge: {
    position: 'absolute',
    top: RFValue(3),
    right: RFValue(3),
    backgroundColor: COLORS.primary,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: RFValue(4),
    paddingVertical: RFValue(2),
    borderRadius: RFValue(4),
    gap: RFValue(2),
  },
  sizeBadgeText: {
    fontSize: RFValue(7),
    fontFamily: FONTS.fontFamilyBold,
    color: '#fff',
  },
  infoSection: {
    flex: 1,
    justifyContent: 'space-between',
  },
  titleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: RFValue(5),
    gap: RFValue(5),
  },
  cartItemTitle: {
    fontSize: RFValue(11.5),
    fontFamily: FONTS.fontFamilyBold,
    color: '#2C2C2C',
    flex: 1,
    lineHeight: RFValue(15),
    letterSpacing: RFValue(0.1),
  },
  deleteBtn: {
    backgroundColor: '#FFE5E5',
    width: RFValue(26),
    height: RFValue(26),
    borderRadius: RFValue(6),
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: 'rgba(255, 68, 68, 0.4)',
    elevation: 1,
    shadowColor: '#FF4444',
    shadowOffset: {width: 0, height: RFValue(1)},
    shadowOpacity: 0.15,
    shadowRadius: RFValue(2),
  },
  priceInfoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: RFValue(6),
    gap: RFValue(6),
  },
  unitPriceContainer: {
    flex: 1,
  },
  unitPriceLabel: {
    fontSize: RFValue(9),
    fontFamily: FONTS.fontFamilyRegular,
    color: '#999',
    marginBottom: RFValue(2),
  },
  unitPriceValue: {
    fontSize: RFValue(11),
    fontFamily: FONTS.fontFamilyBold,
    color: '#666',
  },
  totalPriceContainer: {
    flex: 1,
    alignItems: 'flex-end',
  },
  totalPriceLabel: {
    fontSize: RFValue(9),
    fontFamily: FONTS.fontFamilyRegular,
    color: '#999',
    marginBottom: RFValue(2),
  },
  totalPriceValue: {
    fontSize: RFValue(13),
    fontFamily: FONTS.fontFamilyBold,
    color: COLORS.primary,
  },
  controlsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: RFValue(5),
  },
  quantityBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF2F6',
    borderRadius: RFValue(6),
    borderWidth: 1.5,
    borderColor: '#FFE5EC',
    flex: 1,
    overflow: 'hidden',
    elevation: 1,
    shadowColor: COLORS.primary,
    shadowOffset: {width: 0, height: RFValue(1)},
    shadowOpacity: 0.08,
    shadowRadius: RFValue(2),
    maxWidth: RFValue(110),
  },
  qtyBtn: {
    padding: RFValue(4),
    justifyContent: 'center',
    alignItems: 'center',
    minWidth: RFValue(26),
    minHeight: RFValue(26),
  },
  qtyBtnInner: {
    width: RFValue(16),
    height: RFValue(16),
    borderRadius: RFValue(8),
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: RFValue(1)},
    shadowOpacity: 0.1,
    shadowRadius: RFValue(2),
  },
  qtyBtnMinus: {
    borderRightWidth: 1,
    borderRightColor: '#FFE5EC',
  },
  qtyBtnPlus: {
    borderLeftWidth: 1,
    borderLeftColor: '#FFE5EC',
  },
  qtyBtnDisabled: {
    opacity: 0.4,
  },
  qtyNumberContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: RFValue(2),
    minHeight: RFValue(26),
  },
  qtyText: {
    fontSize: RFValue(12),
    fontFamily: FONTS.fontFamilyBold,
    color: '#2C2C2C',
    textAlign: 'center',
  },
  favoriteBtn: {
    padding: RFValue(4),
    borderRadius: RFValue(6),
    backgroundColor: '#FFF8F8',
    width: RFValue(26),
    height: RFValue(26),
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#FFE5EC',
  },
  favoriteBtnActive: {
    backgroundColor: '#FF6B9D',
    borderColor: '#FF6B9D',
    elevation: 2,
    shadowColor: '#FF6B9D',
    shadowOffset: {width: 0, height: RFValue(1)},
    shadowOpacity: 0.3,
    shadowRadius: RFValue(2),
  },

  // Left Column: Order Summary
  leftColumn: {
    flex: IS_TABLET ? 1 : 1,
    width: IS_TABLET ? 'auto' : '100%',
    minWidth: IS_TABLET ? RFValue(280) : '100%',
    position: IS_TABLET ? 'sticky' : 'relative',
    top: IS_TABLET ? RFValue(0) : 0,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: RFValue(12),
    gap: RFValue(8),
    paddingHorizontal: RFValue(2),
  },
  sectionTitle: {
    fontSize: RFValue(16),
    fontFamily: FONTS.funPlayBold,
    color: COLORS.primary,
    letterSpacing: RFValue(0.2),
  },
  summaryCard: {
    backgroundColor: '#fff',
    borderRadius: RFValue(14),
    padding: RFValue(14),
    elevation: 3,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowOffset: {width: 0, height: RFValue(2)},
    shadowRadius: RFValue(6),
    borderWidth: 1,
    borderColor: '#F0F0F0',
    overflow: 'hidden',
  },
  summaryContent: {
    paddingTop: RFValue(6),
    marginBottom: RFValue(12),
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: RFValue(8),
    paddingVertical: RFValue(1),
  },
  summaryLabel: {
    fontSize: RFValue(11),
    fontFamily: FONTS.fontFamilyRegular,
    color: '#666',
    flex: 1,
    lineHeight: RFValue(16),
  },
  summaryValue: {
    fontSize: RFValue(11),
    fontFamily: FONTS.fontFamilyBold,
    color: '#2C2C2C',
  },
  totalRow: {
    borderTopWidth: 1.5,
    borderTopColor: '#E8E8E8',
    paddingTop: RFValue(10),
    marginTop: RFValue(4),
  },
  totalLabel: {
    fontSize: RFValue(15),
    fontFamily: FONTS.fontFamilyBold,
    color: '#2C2C2C',
    letterSpacing: RFValue(0.2),
  },
  totalValue: {
    fontSize: RFValue(18),
    color: COLORS.primary,
    fontFamily: FONTS.fontFamilyBold,
    letterSpacing: RFValue(0.3),
  },

  // Action Buttons
  actionButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  discountButton: {
    backgroundColor: '#fff',
    borderRadius: RFValue(10),
    padding: RFValue(12),
    marginBottom: RFValue(10),
    borderWidth: 1.5,
    borderColor: '#B8E0F0',
  },
  discountButtonText: {
    fontSize: RFValue(12),
    fontFamily: FONTS.fontFamilyBold,
    color: '#4A90A4',
    flex: 1,
    marginLeft: RFValue(8),
    letterSpacing: RFValue(0.1),
  },
  noteButton: {
    backgroundColor: '#fff',
    borderRadius: RFValue(10),
    padding: RFValue(12),
    marginBottom: RFValue(10),
    borderWidth: 1.5,
    borderColor: '#FFD6E5',
  },
  noteButtonText: {
    fontSize: RFValue(12),
    fontFamily: FONTS.fontFamilyBold,
    color: '#FF6B9D',
    flex: 1,
    marginLeft: RFValue(8),
    letterSpacing: RFValue(0.1),
  },
  inputContainer: {
    marginBottom: RFValue(8),
    marginTop: RFValue(-2),
  },
  discountRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: RFValue(8),
  },
  discountInput: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: RFValue(8),
    padding: RFValue(12),
    fontSize: RFValue(12),
    fontFamily: FONTS.fontFamilyRegular,
    color: '#333',
    borderWidth: 1.5,
    borderColor: '#B8E0F0',
    elevation: 2,
    shadowColor: '#B8E0F0',
    shadowOffset: {width: 0, height: RFValue(2)},
    shadowOpacity: 0.15,
    shadowRadius: RFValue(4),
  },
  applyDiscountButton: {
    backgroundColor: '#4A90A4',
    paddingVertical: RFValue(12),
    paddingHorizontal: RFValue(16),
    justifyContent: 'center',
    alignItems: 'center',
    minWidth: RFValue(52),
    borderRadius: RFValue(8),
    elevation: 3,
    shadowColor: '#4A90A4',
    shadowOffset: {width: 0, height: RFValue(2)},
    shadowOpacity: 0.3,
    shadowRadius: RFValue(4),
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  input: {
    backgroundColor: '#fff',
    borderRadius: RFValue(8),
    padding: RFValue(12),
    fontSize: RFValue(12),
    fontFamily: FONTS.fontFamilyRegular,
    color: '#333',
    borderWidth: 1.5,
    borderColor: '#B8E0F0',
    elevation: 2,
    shadowColor: '#B8E0F0',
    shadowOffset: {width: 0, height: RFValue(2)},
    shadowOpacity: 0.15,
    shadowRadius: RFValue(4),
  },
  noteInputContainer: {
    marginBottom: RFValue(8),
    marginTop: RFValue(-2),
  },
  noteInput: {
    backgroundColor: '#fff',
    borderRadius: RFValue(8),
    padding: RFValue(12),
    fontSize: RFValue(12),
    fontFamily: FONTS.fontFamilyRegular,
    color: '#333',
    borderWidth: 1.5,
    borderColor: '#FFD6E5',
    minHeight: RFValue(80),
    textAlignVertical: 'top',
    elevation: 2,
    shadowColor: '#FFD6E5',
    shadowOffset: {width: 0, height: RFValue(2)},
    shadowOpacity: 0.15,
    shadowRadius: RFValue(4),
  },

  // Order Now Button
  orderNowButton: {
    borderRadius: RFValue(11),
    overflow: 'hidden',
    elevation: 4,
    shadowColor: COLORS.primary,
    shadowOffset: {width: 0, height: RFValue(2)},
    shadowOpacity: 0.25,
    shadowRadius: RFValue(5),
    marginBottom: RFValue(12),
    marginTop: RFValue(2),
  },
  orderNowGradient: {
    paddingVertical: RFValue(11),
    paddingHorizontal: RFValue(16),
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    gap: RFValue(6),
  },
  orderNowText: {
    fontSize: RFValue(13),
    color: '#fff',
    fontFamily: FONTS.fontFamilyBold,
    letterSpacing: RFValue(0.3),
  },

  // Delivery Info
  deliveryInfo: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#F9F9F9',
    padding: RFValue(9),
    borderRadius: RFValue(8),
    marginBottom: RFValue(10),
    gap: RFValue(6),
    borderWidth: 1,
    borderColor: '#F0F0F0',
  },
  deliveryText: {
    fontSize: RFValue(10),
    fontFamily: FONTS.fontFamilyRegular,
    color: '#666',
    flex: 1,
    lineHeight: RFValue(14),
  },

  // Disclaimer
  disclaimer: {
    fontSize: RFValue(9),
    fontFamily: FONTS.fontFamilyRegular,
    color: '#999',
    textAlign: 'center',
    lineHeight: RFValue(13),
    paddingHorizontal: RFValue(4),
  },

  // Empty Cart
  emptyCart: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: RFValue(100),
    paddingHorizontal: RFValue(40),
  },
  emptyCartText: {
    fontSize: RFValue(20),
    fontFamily: FONTS.fontFamilyBold,
    color: COLORS.primary,
    marginTop: RFValue(20),
    marginBottom: RFValue(10),
    letterSpacing: RFValue(0.2),
  },
  emptyCartSubtext: {
    fontSize: RFValue(14),
    fontFamily: FONTS.fontFamilyRegular,
    color: COLORS.grey60,
    textAlign: 'center',
    marginBottom: RFValue(30),
    lineHeight: RFValue(20),
  },
  continueShoppingButton: {
    backgroundColor: COLORS.primary,
    paddingVertical: RFValue(12),
    paddingHorizontal: RFValue(30),
    borderRadius: RFValue(10),
    elevation: 3,
    shadowColor: COLORS.primary,
    shadowOffset: {width: 0, height: RFValue(2)},
    shadowOpacity: 0.25,
    shadowRadius: RFValue(4),
  },
  continueShoppingText: {
    fontSize: RFValue(14),
    color: '#fff',
    fontFamily: FONTS.fontFamilyBold,
    letterSpacing: RFValue(0.2),
  },
});

export default styles;
