import {StyleSheet, Dimensions} from 'react-native';
import {FONTS, COLORS} from '../../../constants';
import {RFValue} from 'react-native-responsive-fontsize';

const {width: SCREEN_WIDTH, height: SCREEN_HEIGHT} = Dimensions.get('window');
const HERO_HEIGHT = SCREEN_HEIGHT * 0.28;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.pinkybg,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: RFValue(30),
  },
  heroSectionWrapper: {
    marginBottom: RFValue(20),
    position: 'relative',
  },
  heroSection: {
    height: HERO_HEIGHT,
  },
  heroSlideContainer: {
    width: '100%',
    height: '100%',
  },
  heroSlideBackground: {
    width: '100%',
    height: '100%',
    overflow: 'hidden',
    shadowColor: COLORS.primary,
    shadowOffset: {
      width: 0,
      height: RFValue(3),
    },
    shadowOpacity: 0.15,
    shadowRadius: RFValue(8),
    elevation: RFValue(5),
  },
  heroSlideBackgroundImage: {
    resizeMode: 'cover',
  },
  heroGradientOverlay: {
    flex: 1,
    alignItems: 'flex-start',
    paddingTop: RFValue(20),
    paddingHorizontal: RFValue(10),
    paddingBottom: RFValue(20),
  },
  heroSlideContent: {
    justifyContent: 'center',
    width: '100%',
  },
  heroMainTitle: {
    fontSize: RFValue(22),
    fontFamily: FONTS.funPlayBold,
    color: '#fff',
    marginBottom: RFValue(5),
    textShadowColor: 'rgba(0, 0, 0, 0.7)',
    textShadowOffset: {width: 0, height: RFValue(3)},
    textShadowRadius: RFValue(6),
    letterSpacing: RFValue(0.5),
  },
  heroSlideTitle: {
    fontSize: RFValue(16),
    fontFamily: FONTS.funPlayBold,
    color: '#fff',
    marginBottom: RFValue(8),
    textShadowColor: 'rgba(0, 0, 0, 0.6)',
    textShadowOffset: {width: 0, height: RFValue(2)},
    textShadowRadius: RFValue(5),
  },
  heroSlideDescription: {
    fontSize: RFValue(15),
    fontFamily: FONTS.fontFamilyRegular,
    color: '#fff',
    marginBottom: RFValue(12),
    lineHeight: RFValue(20),
    width: '50%',
    textShadowColor: 'rgba(0, 0, 0, 0.6)',
    textShadowOffset: {width: 0, height: RFValue(2)},
    textShadowRadius: RFValue(4),
    marginTop: RFValue(10),
  },
  waveContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    width: SCREEN_WIDTH,
    height: RFValue(60),
    zIndex: 100,
    overflow: 'hidden',
    backgroundColor: 'transparent',
  },
  contentWrapper: {
    paddingHorizontal: RFValue(15),
    gap: RFValue(15),
    marginTop: -RFValue(30),
    zIndex: 1000,
  },
  summaryCard: {
    backgroundColor: '#fff',
    borderRadius: RFValue(16),
    padding: RFValue(20),
    elevation: 3,
    shadowColor: COLORS.primary,
    shadowOffset: {
      width: 0,
      height: RFValue(2),
    },
    shadowOpacity: 0.1,
    shadowRadius: RFValue(6),
    borderWidth: RFValue(2),
    borderColor: 'transparent',
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: RFValue(18),
    gap: RFValue(8),
  },
  sectionTitle: {
    fontSize: RFValue(18),
    fontFamily: FONTS.funPlayBold,
    color: COLORS.primary,
  },
  orderItemsList: {
    marginBottom: RFValue(15),
  },
  orderItem: {
    flexDirection: 'row',
    marginBottom: RFValue(15),
    gap: RFValue(12),
    paddingBottom: RFValue(15),
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  orderItemImage: {
    width: RFValue(70),
    height: RFValue(70),
    borderRadius: RFValue(10),
    overflow: 'hidden',
  },
  discountBadge: {
    position: 'absolute',
    top: RFValue(5),
    left: RFValue(5),
    backgroundColor: COLORS.secondary,
    paddingHorizontal: RFValue(5),
    paddingVertical: RFValue(2),
    borderRadius: RFValue(5),
  },
  discountText: {
    color: '#fff',
    fontSize: RFValue(9),
    fontFamily: FONTS.fontFamilyBold,
  },
  orderItemInfo: {
    flex: 1,
    justifyContent: 'space-between',
  },
  orderItemTitle: {
    fontSize: RFValue(13),
    fontFamily: FONTS.fontFamilyBold,
    color: '#333',
    marginBottom: RFValue(5),
    // textAlign: 'right',
  },
  orderItemQuantity: {
    fontSize: RFValue(11),
    fontFamily: FONTS.fontFamilyRegular,
    color: '#666',
    marginBottom: RFValue(5),
    // textAlign: 'right',
  },
  orderItemPrice: {
    fontSize: RFValue(14),
    fontFamily: FONTS.fontFamilyBold,
    color: COLORS.primary,
    // textAlign: 'right',
  },
  divider: {
    height: 1,
    backgroundColor: '#E0E0E0',
    marginVertical: RFValue(15),
  },
  priceBreakdown: {
    marginBottom: RFValue(15),
  },
  priceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: RFValue(8),
    alignItems: 'center',
  },
  priceLabel: {
    fontSize: RFValue(12),
    fontFamily: FONTS.fontFamilyRegular,
    color: '#666',
    // textAlign: 'right',
  },
  priceValue: {
    fontSize: RFValue(12),
    fontFamily: FONTS.fontFamilyBold,
    color: '#333',
    textAlign: 'left',
  },
  discountValue: {
    color: COLORS.secondary,
  },
  totalRow: {
    borderTopWidth: 1,
    borderTopColor: '#E0E0E0',
    paddingTop: RFValue(12),
    marginTop: RFValue(8),
  },
  totalLabel: {
    fontSize: RFValue(16),
    fontFamily: FONTS.fontFamilyBold,
    color: '#333',
    // textAlign: 'right',
  },
  totalValue: {
    fontSize: RFValue(18),
    fontFamily: FONTS.fontFamilyBold,
    color: COLORS.primary,
    textAlign: 'left',
  },
  securityMessage: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF2F6',
    padding: RFValue(12),
    borderRadius: RFValue(10),
    gap: RFValue(8),
    marginTop: RFValue(5),
  },
  securityText: {
    flex: 1,
    fontSize: RFValue(10),
    fontFamily: FONTS.fontFamilyRegular,
    color: '#666',
    // textAlign: 'right',
    lineHeight: RFValue(16),
  },
  formSection: {
    width: '100%',
  },
  section: {
    backgroundColor: '#fff',
    borderRadius: RFValue(16),
    padding: RFValue(20),
    marginBottom: RFValue(15),
    elevation: 3,
    shadowColor: COLORS.primary,
    shadowOffset: {
      width: 0,
      height: RFValue(2),
    },
    shadowOpacity: 0.1,
    shadowRadius: RFValue(6),
    borderWidth: RFValue(2),
    borderColor: 'transparent',
  },
  inputContainer: {
    marginBottom: RFValue(15),
  },
  label: {
    fontSize: RFValue(12),
    fontFamily: FONTS.fontFamilyMedium,
    color: '#333',
    marginBottom: RFValue(8),
    // textAlign: 'right',
  },
  requiredStar: {
    color: COLORS.primary,
    fontSize: RFValue(12),
  },
  inputWrapper: {
    borderRadius: RFValue(12),
    backgroundColor: '#FAFAFA',
    borderWidth: 2,
    borderColor: '#E8E8E8',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.04,
    shadowRadius: 3,
    elevation: 2,
  },
  inputWrapperFocused: {
    borderColor: COLORS.primary,
    backgroundColor: '#FFF',
    shadowColor: COLORS.primary,
    shadowOpacity: 0.15,
    shadowRadius: 5,
    elevation: 3,
  },
  input: {
    paddingHorizontal: RFValue(15),
    paddingVertical: RFValue(12),
    fontSize: RFValue(12),
    fontFamily: FONTS.fontFamilyRegular,
    color: '#333',
    // textAlign: 'right',
  },
  textAreaWrapper: {
    minHeight: RFValue(100),
  },
  textArea: {
    paddingTop: RFValue(12),
    textAlignVertical: 'top',
  },
  row: {
    flexDirection: 'row',
    gap: RFValue(12),
  },
  halfWidth: {
    flex: 1,
  },
  dropdown: {
    borderRadius: RFValue(12),
    backgroundColor: '#FAFAFA',
    borderWidth: 2,
    borderColor: '#E8E8E8',
    paddingHorizontal: RFValue(15),
    paddingVertical: RFValue(12),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.04,
    shadowRadius: 3,
    elevation: 2,
  },
  dropdownFocused: {
    borderColor: COLORS.primary,
    backgroundColor: '#FFF',
    shadowColor: COLORS.primary,
    shadowOpacity: 0.15,
    shadowRadius: 5,
    elevation: 3,
  },
  dropdownText: {
    fontSize: RFValue(10),
    fontFamily: FONTS.fontFamilyRegular,
    color: '#333',
    flex: 1,
    // textAlign: 'right',
  },
  dropdownPlaceholder: {
    color: COLORS.grey60,
  },
  dropdownDisabled: {
    opacity: 0.6,
    backgroundColor: '#F5F5F5',
  },
  dropdownList: {
    backgroundColor: COLORS.white,
    borderRadius: RFValue(10),
    marginTop: RFValue(5),
    borderWidth: 1.5,
    borderColor: COLORS.primary300,
    shadowColor: COLORS.primary,
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 10,
    overflow: 'hidden',
    position: 'absolute',
    top: '100%',
    left: 0,
    right: 0,
    zIndex: 9999,
    maxHeight: RFValue(150),
  },
  dropdownScrollView: {
    maxHeight: RFValue(150),
  },
  dropdownItem: {
    padding: RFValue(10),
    borderBottomWidth: 1,
    borderBottomColor: '#F5F5F5',
    backgroundColor: COLORS.white,
    minHeight: RFValue(40),
    justifyContent: 'center',
  },
  dropdownItemText: {
    fontSize: RFValue(11),
    fontFamily: FONTS.fontFamilyRegular,
    color: '#333',
    // textAlign: 'right',
  },
  paymentOption: {
    borderWidth: 2,
    borderColor: '#E8E8E8',
    borderRadius: RFValue(14),
    padding: RFValue(16),
    marginBottom: RFValue(12),
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  paymentOptionSelected: {
    borderColor: COLORS.primary,
    backgroundColor: '#FFF2F6',
    shadowColor: COLORS.primary,
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
    borderWidth: 2.5,
  },
  paymentOptionContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: RFValue(12),
  },
  radioButton: {
    width: RFValue(22),
    height: RFValue(22),
    borderRadius: RFValue(11),
    borderWidth: 2.5,
    borderColor: '#D0D0D0',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
  },
  radioButtonSelected: {
    borderColor: COLORS.primary,
    backgroundColor: '#FFF2F6',
  },
  radioButtonInner: {
    width: RFValue(10),
    height: RFValue(10),
    borderRadius: RFValue(5),
    backgroundColor: COLORS.primary,
  },
  paymentIconWrapper: {
    width: RFValue(42),
    height: RFValue(42),
    borderRadius: RFValue(12),
    backgroundColor: '#F8F8F8',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E8E8E8',
  },
  paymentIconWrapperActive: {
    backgroundColor: '#FFF2F6',
    borderColor: COLORS.primary,
    borderWidth: 1.5,
  },
  paymentOptionText: {
    flex: 1,
  },
  paymentOptionTitle: {
    fontSize: RFValue(14),
    fontFamily: FONTS.fontFamilyBold,
    color: '#333',
    marginBottom: RFValue(4),
    // textAlign: 'right',
  },
  paymentOptionDescription: {
    fontSize: RFValue(11),
    fontFamily: FONTS.fontFamilyRegular,
    color: '#666',
    lineHeight: RFValue(16),
    // textAlign: 'right',
  },
  paymentCardsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: RFValue(10),
    marginTop: RFValue(12),
    paddingTop: RFValue(12),
    borderTopWidth: 1.5,
    borderTopColor: '#E8E8E8',
  },
  paymentCardLogo: {
    width: RFValue(45),
    height: RFValue(28),
  },
  madaContainer: {
    width: RFValue(65),
    height: RFValue(40),
    justifyContent: 'center',
    alignItems: 'center',
  },
  paymentCardLogoLarge: {
    width: RFValue(75),
    height: RFValue(45),
  },
  bottomButtonContainer: {
    paddingHorizontal: RFValue(15),
    paddingTop: RFValue(15),
    paddingBottom: RFValue(20),
  },
  completeOrderButton: {
    borderRadius: RFValue(14),
    overflow: 'hidden',
    elevation: 6,
    shadowColor: COLORS.primary,
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.25,
    shadowRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  completeOrderGradient: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: RFValue(12),
    paddingHorizontal: RFValue(20),
    gap: RFValue(8),
  },
  buttonIconWrapper: {
    width: RFValue(24),
    height: RFValue(24),
    borderRadius: RFValue(12),
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  completeOrderText: {
    fontSize: RFValue(14),
    fontFamily: FONTS.fontFamilyBold,
    color: '#fff',
    letterSpacing: 0.3,
  },
});

export default styles;

