import {StyleSheet, Dimensions} from 'react-native';
import {FONTS, COLORS} from '../../../constants';
import {RFValue} from 'react-native-responsive-fontsize';

const {height: SCREEN_HEIGHT} = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.pinkybg,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: RFValue(120),
  },
  headerSection: {
    backgroundColor: COLORS.white,
    paddingHorizontal: RFValue(18),
    paddingTop: RFValue(18),
    paddingBottom: RFValue(16),
    marginBottom: RFValue(16),
    borderBottomWidth: RFValue(1),
    borderBottomColor: COLORS.grey20,
  },
  totalOrdersCard: {
    flex: 1,
    paddingVertical: RFValue(10),
    paddingHorizontal: RFValue(2),
    borderRadius: RFValue(12),
    borderWidth: 2,
    borderColor: 'rgba(226, 61, 136, 0.3)',
    backgroundColor: COLORS.primary100,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 0,
    minHeight: RFValue(70),
  },
  totalOrdersCount: {
    fontSize: RFValue(18),
    fontFamily: FONTS.fontFamilyBold,
    color: COLORS.primary,
    marginBottom: RFValue(2),
  },
  totalOrdersLabel: {
    fontSize: RFValue(9),
    fontFamily: FONTS.fontFamilyMedium,
    color: COLORS.primary,
  },
  mainTitle: {
    fontSize: RFValue(22),
    fontFamily: FONTS.funPlayBold,
    color: COLORS.primary,
    marginBottom: RFValue(16),
  },
  statusSummary: {
    flexDirection: 'row',
    gap: RFValue(6),
    marginBottom: RFValue(16),
    justifyContent: 'space-between',
    alignItems: 'stretch',
  },
  statusCard: {
    flex: 1,
    paddingVertical: RFValue(10),
    paddingHorizontal: RFValue(2),
    borderRadius: RFValue(12),
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 0,
    minHeight: RFValue(70),
  },
  statusCardActive: {
    borderWidth: 3,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: RFValue(4),
    },
    shadowOpacity: 0.25,
    shadowRadius: RFValue(10),
    elevation: 8,
  },
  statusCardCount: {
    fontSize: RFValue(18),
    fontFamily: FONTS.fontFamilyBold,
    marginBottom: RFValue(2),
  },
  statusCardLabel: {
    fontSize: RFValue(9),
    fontFamily: FONTS.fontFamilyMedium,
  },
  filterTabsContainer: {
    marginHorizontal: RFValue(-18),
    paddingHorizontal: RFValue(18),
    alignSelf: 'center',
  },
  filterTabs: {
    flexDirection: 'row',
    gap: RFValue(6),
  },
  filterTab: {
    paddingHorizontal: RFValue(15),
    paddingVertical: RFValue(5),
    borderRadius: RFValue(20),
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.grey20,
    minHeight: RFValue(40),
    justifyContent: 'center',
    alignItems: 'center',
  },
  filterTabActive: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
    shadowColor: COLORS.primary,
    shadowOffset: {
      width: 0,
      height: RFValue(3),
    },
    shadowOpacity: 0.4,
    shadowRadius: RFValue(6),
    elevation: 5,
  },
  filterTabText: {
    fontSize: RFValue(12),
    fontFamily: FONTS.fontFamilyMedium,
    color: COLORS.darkGray,
  },
  filterTabTextActive: {
    color: COLORS.white,
    fontFamily: FONTS.fontFamilyBold,
  },
  ordersContainer: {
    paddingHorizontal: RFValue(18),
    gap: RFValue(16),
  },
  orderCard: {
    backgroundColor: COLORS.white,
    borderRadius: RFValue(16),
    padding: RFValue(14),
    shadowColor: COLORS.primary,
    shadowOffset: {
      width: 0,
      height: RFValue(2),
    },
    shadowOpacity: 0.06,
    shadowRadius: RFValue(10),
    elevation: 5,
    borderWidth: 1,
    borderColor: 'rgba(226, 61, 136, 0.1)',
    marginBottom: RFValue(2),
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: RFValue(12),
    paddingBottom: RFValue(10),
    borderBottomWidth: 1,
    borderBottomColor: COLORS.grey20,
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: RFValue(10),
    paddingVertical: RFValue(5),
    borderRadius: RFValue(12),
    borderWidth: 1.5,
    gap: RFValue(5),
  },
  statusIcon: {
    marginRight: RFValue(2),
  },
  statusText: {
    fontSize: RFValue(10),
    fontFamily: FONTS.fontFamilyBold,
  },
  orderId: {
    fontSize: RFValue(12),
    fontFamily: FONTS.fontFamilyBold,
    color: COLORS.primary,
    backgroundColor: COLORS.primary100,
    paddingHorizontal: RFValue(8),
    paddingVertical: RFValue(4),
    borderRadius: RFValue(8),
  },
  orderContent: {
    flexDirection: 'row',
    gap: RFValue(12),
    marginBottom: RFValue(12),
  },
  imageSection: {
    width: RFValue(100),
    height: RFValue(100),
    borderRadius: RFValue(14),
    overflow: 'hidden',
    backgroundColor: COLORS.lightGrey,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: RFValue(2),
    },
    shadowOpacity: 0.08,
    shadowRadius: RFValue(4),
    elevation: 3,
  },
  orderImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  placeholderImage: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.grey20,
  },
  infoSection: {
    flex: 1,
    justifyContent: 'space-between',
  },
  dateTimeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: RFValue(6),
    marginBottom: RFValue(6),
  },
  dateText: {
    fontSize: RFValue(11),
    fontFamily: FONTS.fontFamilyRegular,
    color: COLORS.darkGray,
    flex: 1,
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: RFValue(6),
    marginBottom: RFValue(8),
    paddingVertical: RFValue(3),
    paddingHorizontal: RFValue(6),
    backgroundColor: COLORS.primary100,
    borderRadius: RFValue(6),
    alignSelf: 'flex-start',
  },
  itemsText: {
    fontSize: RFValue(11),
    fontFamily: FONTS.fontFamilyBold,
    color: COLORS.primary,
  },
  priceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: RFValue(4),
    paddingTop: RFValue(8),
    borderTopWidth: 1,
    borderTopColor: COLORS.grey20,
  },
  totalLabel: {
    fontSize: RFValue(12),
    fontFamily: FONTS.fontFamilyMedium,
    color: COLORS.darkGray,
  },
  totalPrice: {
    fontSize: RFValue(18),
    fontFamily: FONTS.fontFamilyBold,
    color: COLORS.primary,
  },
  detailsSection: {
    paddingTop: RFValue(12),
    paddingBottom: RFValue(10),
    borderTopWidth: 1,
    borderTopColor: COLORS.grey20,
    gap: RFValue(8),
    marginBottom: RFValue(12),
    backgroundColor: COLORS.lightGrey,
    paddingHorizontal: RFValue(10),
    borderRadius: RFValue(10),
  },
  detailItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: RFValue(8),
  },
  detailText: {
    flex: 1,
    fontSize: RFValue(11),
    fontFamily: FONTS.fontFamilyRegular,
    color: COLORS.darkGray,
    lineHeight: RFValue(18),
    marginTop: -RFValue(3),
  },
  actionButtons: {
    flexDirection: 'row',
    gap: RFValue(8),
  },
  viewDetailsBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: RFValue(10),
    paddingHorizontal: RFValue(8),
    borderRadius: RFValue(12),
    backgroundColor: COLORS.primary100,
    borderWidth: 1.5,
    borderColor: 'rgba(226, 61, 136, 0.2)',
    gap: RFValue(5),
    minHeight: RFValue(40),
  },
  viewDetailsBtnText: {
    fontSize: RFValue(11),
    fontFamily: FONTS.fontFamilyBold,
    color: COLORS.primary,
  },
  reorderBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: RFValue(10),
    paddingHorizontal: RFValue(8),
    borderRadius: RFValue(12),
    backgroundColor: COLORS.primary,
    gap: RFValue(5),
    minHeight: RFValue(40),
    shadowColor: COLORS.primary,
    shadowOffset: {
      width: 0,
      height: RFValue(3),
    },
    shadowOpacity: 0.3,
    shadowRadius: RFValue(6),
    elevation: 5,
  },
  reorderBtnText: {
    fontSize: RFValue(11),
    fontFamily: FONTS.fontFamilyBold,
    color: COLORS.white,
  },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: RFValue(80),
    paddingHorizontal: RFValue(40),
  },
  emptyIconContainer: {
    width: RFValue(120),
    height: RFValue(120),
    borderRadius: RFValue(60),
    backgroundColor: COLORS.grey20,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: RFValue(20),
  },
  emptyStateTitle: {
    fontSize: RFValue(18),
    fontFamily: FONTS.funPlayBold,
    color: COLORS.darkGray,
    marginBottom: RFValue(8),
  },
  emptyStateText: {
    fontSize: RFValue(13),
    fontFamily: FONTS.fontFamilyRegular,
    color: COLORS.grey60,
    textAlign: 'center',
    lineHeight: RFValue(20),
  },
  // Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  modalContainer: {
    backgroundColor: COLORS.white,
    borderTopLeftRadius: RFValue(20),
    borderTopRightRadius: RFValue(20),
    height: SCREEN_HEIGHT * 0.95,
    paddingTop: RFValue(12),
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: RFValue(-4),
    },
    shadowOpacity: 0.25,
    shadowRadius: RFValue(20),
    elevation: 20,
  },
  modalScrollView: {
    flex: 1,
  },
  modalContent: {
    paddingBottom: RFValue(100),
    flexGrow: 1,
  },
  modalHeader: {
    paddingHorizontal: RFValue(16),
    paddingTop: RFValue(16),
    paddingBottom: RFValue(12),
    borderBottomWidth: 1,
    borderBottomColor: COLORS.grey20,
  },
  modalHeaderTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: RFValue(10),
  },
  modalStatusBadge: {
    paddingHorizontal: RFValue(10),
    paddingVertical: RFValue(5),
    borderRadius: RFValue(12),
    borderWidth: 1.5,
  },
  modalStatusText: {
    fontSize: RFValue(9),
    fontFamily: FONTS.fontFamilyBold,
  },
  modalCloseButton: {
    width: RFValue(28),
    height: RFValue(28),
    borderRadius: RFValue(14),
    backgroundColor: COLORS.grey20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalTitle: {
    fontSize: RFValue(16),
    fontFamily: FONTS.fontFamilyBold,
    color: COLORS.primary,
    marginBottom: RFValue(4),
  },
  modalDate: {
    fontSize: RFValue(10),
    fontFamily: FONTS.fontFamilyRegular,
    color: COLORS.darkGray,
  },
  modalSummaryCard: {
    backgroundColor: COLORS.primary100,
    marginHorizontal: RFValue(16),
    marginTop: RFValue(12),
    marginBottom: RFValue(10),
    padding: RFValue(12),
    borderRadius: RFValue(14),
    borderWidth: 1,
    borderColor: 'rgba(226, 61, 136, 0.15)',
  },
  modalSummaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  modalSummaryLeft: {
    flex: 1,
  },
  modalSummaryLabel: {
    fontSize: RFValue(10),
    fontFamily: FONTS.fontFamilyMedium,
    color: COLORS.darkGray,
    marginBottom: RFValue(4),
  },
  modalSummaryPrice: {
    fontSize: RFValue(20),
    fontFamily: FONTS.fontFamilyBold,
    color: COLORS.primary,
  },
  modalImageContainer: {
    width: RFValue(70),
    height: RFValue(70),
    borderRadius: RFValue(12),
    overflow: 'hidden',
    position: 'relative',
  },
  modalImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  modalPlaceholderImage: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.grey20,
  },
  modalImageBadge: {
    position: 'absolute',
    bottom: RFValue(4),
    right: RFValue(4),
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    paddingHorizontal: RFValue(6),
    paddingVertical: RFValue(3),
    borderRadius: RFValue(6),
    minWidth: RFValue(24),
    alignItems: 'center',
  },
  modalImageBadgeText: {
    fontSize: RFValue(9),
    fontFamily: FONTS.fontFamilyBold,
    color: COLORS.white,
  },
  modalInfoCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: RFValue(10),
    backgroundColor: COLORS.lightGrey,
    marginHorizontal: RFValue(16),
    marginBottom: RFValue(8),
    padding: RFValue(12),
    borderRadius: RFValue(12),
  },
  modalInfoText: {
    flex: 1,
    fontSize: RFValue(11),
    fontFamily: FONTS.fontFamilyRegular,
    color: COLORS.darkGray,
    lineHeight: RFValue(18),
  },
  modalSectionTitle: {
    fontSize: RFValue(12),
    fontFamily: FONTS.fontFamilyBold,
    color: COLORS.primary,
    marginBottom: RFValue(10),
  },
  modalProductsSection: {
    paddingHorizontal: RFValue(16),
    paddingTop: RFValue(12),
    paddingBottom: RFValue(12),
  },
  modalProductItem: {
    flexDirection: 'row',
    gap: RFValue(10),
    marginBottom: RFValue(12),
    paddingBottom: RFValue(12),
    borderBottomWidth: 1,
    borderBottomColor: COLORS.grey20,
  },
  modalProductImage: {
    width: RFValue(60),
    height: RFValue(60),
    borderRadius: RFValue(10),
    overflow: 'hidden',
    backgroundColor: COLORS.lightGrey,
  },
  modalProductImageStyle: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  modalProductPlaceholder: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.grey20,
  },
  modalProductInfo: {
    flex: 1,
    justifyContent: 'space-between',
  },
  modalProductName: {
    fontSize: RFValue(11),
    fontFamily: FONTS.fontFamilyBold,
    color: COLORS.darkGray,
    marginBottom: RFValue(6),
    lineHeight: RFValue(16),
  },
  modalProductActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  modalProductPrice: {
    fontSize: RFValue(12),
    fontFamily: FONTS.fontFamilyBold,
    color: COLORS.primary,
  },
  modalQuantityControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: RFValue(8),
    backgroundColor: COLORS.lightGrey,
    borderRadius: RFValue(10),
    paddingHorizontal: RFValue(6),
    paddingVertical: RFValue(4),
  },
  modalQuantityButton: {
    width: RFValue(24),
    height: RFValue(24),
    borderRadius: RFValue(12),
    backgroundColor: COLORS.white,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.grey20,
  },
  modalQuantityButtonActive: {
    backgroundColor: COLORS.primary100,
    borderColor: COLORS.primary,
  },
  modalQuantityText: {
    fontSize: RFValue(11),
    fontFamily: FONTS.fontFamilyBold,
    color: COLORS.darkGray,
    minWidth: RFValue(20),
    textAlign: 'center',
  },
  modalReorderButton: {
    marginHorizontal: RFValue(16),
    marginTop: RFValue(12),
    backgroundColor: COLORS.primary,
    paddingVertical: RFValue(9),
    borderRadius: RFValue(12),
    alignItems: 'center',
    shadowColor: COLORS.primary,
    shadowOffset: {
      width: 0,
      height: RFValue(3),
    },
    shadowOpacity: 0.35,
    shadowRadius: RFValue(6),
    elevation: 5,
  },
  modalReorderButtonText: {
    fontSize: RFValue(11),
    fontFamily: FONTS.fontFamilyBold,
    color: COLORS.white,
  },
  modalDisclaimer: {
    fontSize: RFValue(9),
    fontFamily: FONTS.fontFamilyRegular,
    color: COLORS.grey60,
    textAlign: 'center',
    marginTop: RFValue(8),
    marginHorizontal: RFValue(16),
    lineHeight: RFValue(14),
  },
});

export default styles;
